[tool.poetry]
name = "kiri-pathfinding"
version = "1.2.0"
description = "A toy module to generate a map and find the shortest path from two points on the map"
authors = [ "anthony <mrchowpoor@gmail.com>" ]
license = "MIT"
repository = "https://github.com/kiri-chow/kiri-pathfinding"
readme = "README.md"
dev-dependencies = { }

  [tool.poetry.dependencies]
  python = "^3.9"
  numba = "^0.56.3"
  numpy = "^1.23.4"
  matplotlib = "^3.6.1"
  scikit-learn = "^1.1.2"
  scikit-image = "^0.19.3"

[build-system]
requires = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"
