[tool.poetry]
name = "netlink-sap-monitor"
version = "0.0.3"
description = "SAP Monitoring"
license = "MIT"
authors = ["Bernhard Radermacher <bernhard.radermacher@netlink-consulting.com>"]
readme = "README.md"
repository = "https://gitlab.com/netlink_python/netlink-sap-monitor"
keywords = ["sap monitoring"]
classifiers = ["Topic :: Software Development"]
packages = [ { include = "netlink/sap/monitor" } ]

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
netlink-core = ">^0.0.4"
netlink-logging = ">^0.1.10"

[tool.poetry.dev-dependencies]
black = "^22.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
