[tool.poetry]
name = "timetable-cli"
version = "0.17.0"
description = ""
authors = ["0djentd"]
readme = "README.md"
packages = [{include = "timetable_cli"}]

[tool.poetry.scripts]
timetable-cli = "timetable_cli.cli:cli"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"
rich = "^12.6.0"
appdirs = "^1.4.4"
interactive-select = "^0.4.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
bump2version = "^1.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
