[build-system]
requires = ["Hatchling"]
build-backend = "hatchling.build"

[project]
name = "ipay_python"
version = "0.1.0"
authors = [
    { name="gigamarr", email="marsagishviligig@gmail.com" }
]
description = "Low-level wrapper over Bank of Georgia's payment gateway ipay."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
"Homepage" = "https://github.com/gigamarr/ipay_python"
"Bug Tracker" = "https://github.com/gigamarr/ipay_python/issues"
