[tool.poetry]
name = "gitleaks-py"
version = "0.3.1"
description = ""
authors = ["Pat <patrick.turner@nhs.net>"]
readme = "README.md"
packages = [{include = "gitleaks_py"}]

[tool.poetry.dependencies]
python = "^3.10"
tomli = "^2.0.1"
requests = "^2.28.1"
tomli-w = "^1.0.0"
click = "^8.1.3"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
