[tool.poetry]
name = "netlink-datadog-core"
version = "0.0.3"
description = "Integration for Datadog (Core)"
license = "MIT"
authors = ["Bernhard Radermacher <bernhard.radermacher@netlink-consulting.com>"]
readme = "README.md"
repository = "https://gitlab.com/netlink_python/netlink-datadog-core"
keywords = ["monitoring datadog"]
classifiers = ["Topic :: Software Development"]
packages = [ { include = "netlink/datadog/core" } ]

[tool.poetry.scripts]
validate_api_key = 'netlink.datadog.core.validate_api_key:validate_api_key_cli'

[tool.poetry.dependencies]
python = ">=3.7,<3.11"
netlink-logging = "^0.1.9"
PyYAML = "^6.0"
datadog-api-client = "^2.5.0"

[tool.poetry.dev-dependencies]
black = "^22.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py37', 'py38', 'py39', 'py310']
include = '\.pyi?$'
